# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-IdentServer
version:      0.54
version_from: IdentServer.pm
installdirs:  site
requires:
    Config::IniFiles:              2.3
    Net::Server::Fork:             0.8
    Net::Telnet:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
